## Setup

In [1]:
import pandas as pd
import numpy as np
import os
from langchain_community.document_loaders import PyPDFLoader, UnstructuredPDFLoader, PyPDFium2Loader
from langchain.document_loaders import PyPDFDirectoryLoader, DirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from pathlib import Path
import random
import ollama
import networkx as nx


## Input data directory
data_dir = "PFAS_test"
inputdirectory = Path(f"./data_input/{data_dir}")
## This is where the output csv files will be written
out_dir = data_dir
outputdirectory = Path(f"./data_output/{out_dir}")

## Load Documents

In [2]:
## Dir PDF Loader
#loader = PyPDFDirectoryLoader(inputdirectory)
## File Loader
#loader = PyPDFLoader("./data/MedicalDocuments/orf-path_health-n1.pdf")
loader = DirectoryLoader(inputdirectory, show_progress=True)
documents = loader.load()

100%|██████████| 1/1 [00:01<00:00,  1.40s/it]

## Extract Concepts

In [3]:
## This function uses the helpers/prompt function to extract concepts from text
from helpers.df_helpers import docs2Graph

If regenerate is set to True then the dataframes are regenerated and Both the dataframes are written in the csv format so we dont have to calculate them again. 

        dfne = dataframe of edges

        df = dataframe of chunks


Else the dataframes are read from the output directory

In [4]:
# To regenerate the graph with LLM, set this to True
regenerate = True

if regenerate:
    # Generate concepts list from full text documents (no chunking)
    G_graph = docs2Graph(documents, model='zephyr:latest')
    # Convert to DataFrame from the graph
    dfg1 = nx.to_pandas_edgelist(G_graph)

Generating triples...
{
  "nodes": [
    {
      "id": "PDMS"
    },
    {
      "id": "carbon_black"
    },
    {
      "id": "iron(II) sulfate"
    },
    {
      "id": "hydrogen_peroxide"
    },
    {
      "id": "zinc oxide"
    },
    {
      "id": "lactic_acid"
    },
    {
      "id": "polyethylene_oxide"
    },
    {
      "id": "lithium salt"
    },
    {
      "id": "ceramic nanoparticles"
    },
    {
      "id": "plasticizers"
    },
    {
      "id": "chitosan"
    },
    {
      "id": "genipin"
  },
  ],
  "edges": [
    {
      "source": "PDMS",
      "target": "carbon_black",
      "relation": "combine to create a flexible, piezoresistive matrix ideal for embedding strain sensors in load-bearing tissue constructs."
    },
    {
      "source": "iron(II) sulfate",
      "target": "hydrogen_peroxide",
      "relation": "interplay during oxidative crosslinking of matrix proteins for the mechanical resilience of engineered bone grafts."
    },
    {
      "source": "zinc oxide",
      "target": "lactic_acid",
      "relation": "promote antibacterial activity and osteoinductivity in bioresorbable scaffold coatings."
    },
    {
      "source": "polyethylene_oxide",
      "target": "lithium salt",
      "target": "ceramic nanoparticles",
      "target": "plasticizers",
      "relation": "produce a solid polymer electrolyte useful for biosensing applications integrated into smart bone implants."
    },
    {
      "source": "chitosan",
      "target": "genipin",
      "relation": "crosslink to form a biocompatible, elastic hydrogel matrix for cartilage and soft-tissue regeneration."
  }
]
}=== RAW LLM RESPONSE ===
{
  "nodes": [
    {
      "id": "PDMS"
    },
    {
      "id": "carbon_black"
    },
    {
      "id": "iron(II) sulfate"
    },
    {
      "id": "hydrogen_peroxide"
    },
    {
      "id": "zinc oxide"
    },
    {
      "id": "lactic_acid"
    },
    {
      "id": "polyethylene_oxide"
    },
    {
      "id": "lithium salt"
    },
    {
      "id": "ceramic nanoparticles"
    },
    {
      "id": "plasticizers"
    },
    {
      "id": "chitosan"
    },
    {
      "id": "genipin"
  },
  ],
  "edges": [
    {
      "source": "PDMS",
      "target": "carbon_black",
      "relation": "combine to create a flexible, piezoresistive matrix ideal for embedding strain sensors in load-bearing tissue constructs."
    },
    {
      "source": "iron(II) sulfate",
      "target": "hydrogen_peroxide",
      "relation": "interplay during oxidative crosslinking of matrix proteins for the mechanical resilience of engineered bone grafts."
    },
    {
      "source": "zinc oxide",
      "target": "lactic_acid",
      "relation": "promote antibacterial activity and osteoinductivity in bioresorbable scaffold coatings."
    },
    {
      "source": "polyethylene_oxide",
      "target": "lithium salt",
      "target": "ceramic nanoparticles",
      "target": "plasticizers",
      "relation": "produce a solid polymer electrolyte useful for biosensing applications integrated into smart bone implants."
    },
    {
      "source": "chitosan",
      "target": "genipin",
      "relation": "crosslink to form a biocompatible, elastic hydrogel matrix for cartilage and soft-tissue regeneration."
  }
]
}
=== CLEANED ===
{
  "nodes": [
    {
      "id": "PDMS"
    },
    {
      "id": "carbon_black"
    },
    {
      "id": "iron(II) sulfate"
    },
    {
      "id": "hydrogen_peroxide"
    },
    {
      "id": "zinc oxide"
    },
    {
      "id": "lactic_acid"
    },
    {
      "id": "polyethylene_oxide"
    },
    {
      "id": "lithium salt"
    },
    {
      "id": "ceramic nanoparticles"
    },
    {
      "id": "plasticizers"
    },
    {
      "id": "chitosan"
    },
    {
      "id": "genipin"
  }],
  "edges": [
    {
      "source": "PDMS",
      "target": "carbon_black",
      "relation": "combine to create a flexible, piezoresistive matrix ideal for embedding strain sensors in load-bearing tissue constructs."
    },
    {
      "source": "iron(II) sulfate",
      "target": "hydrogen_peroxide",
      "relation": "interplay during oxidative crosslinking of matrix proteins for the mechanical resilience of engineered bone grafts."
    },
    {
      "source": "zinc oxide",
      "target": "lactic_acid",
      "relation": "promote antibacterial activity and osteoinductivity in bioresorbable scaffold coatings."
    },
    {
      "source": "polyethylene_oxide",
      "target": "lithium salt",
      "target": "ceramic nanoparticles",
      "target": "plasticizers",
      "relation": "produce a solid polymer electrolyte useful for biosensing applications integrated into smart bone implants."
    },
    {
      "source": "chitosan",
      "target": "genipin",
      "relation": "crosslink to form a biocompatible, elastic hydrogel matrix for cartilage and soft-tissue regeneration."
  }
]
}
Generated graph with 12 nodes and 5 edges.

In [5]:
print(type(G_graph))

<class 'NoneType'>

## Calculating contextual proximity

In [7]:
def contextual_proximity(df: pd.DataFrame) -> pd.DataFrame:
    ## Melt the dataframe into a list of nodes
    dfg_long = pd.melt(
        df, id_vars=["chunk_id"], value_vars=["node_1", "node_2"], value_name="node"
    )
    dfg_long.drop(columns=["variable"], inplace=True)
    # Self join with chunk id as the key will create a link between terms occuring in the same text chunk.
    dfg_wide = pd.merge(dfg_long, dfg_long, on="chunk_id", suffixes=("_1", "_2"))
    # drop self loops
    self_loops_drop = dfg_wide[dfg_wide["node_1"] == dfg_wide["node_2"]].index
    dfg2 = dfg_wide.drop(index=self_loops_drop).reset_index(drop=True)
    ## Group and count edges.
    dfg2 = (
        dfg2.groupby(["node_1", "node_2"])
        .agg({"chunk_id": [",".join, "count"]})
        .reset_index()
    )
    dfg2.columns = ["node_1", "node_2", "chunk_id", "count"]
    dfg2.replace("", np.nan, inplace=True)
    dfg2.dropna(subset=["node_1", "node_2"], inplace=True)
    # Drop edges with 1 count
    dfg2 = dfg2[dfg2["count"] != 1]
    dfg2["edge"] = "contextual proximity"
    return dfg2


dfg2 = contextual_proximity(dfg1)
dfg2.tail()

,node_1,node_2,chunk_id,count,edge
2827,world-class health facilities,nhm strategies,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",10,contextual proximity
2828,world-class health facilities,rural areas,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",2,contextual proximity
2829,world-class health facilities,social norms,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",2,contextual proximity
2830,world-class health facilities,urban areas,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",2,contextual proximity
2831,world-class health facilities,urban slums,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",2,contextual proximity

### Merge both the dataframes

In [8]:
dfg = pd.concat([dfg1, dfg2], axis=0)
dfg = (
    dfg.groupby(["node_1", "node_2"])
    .agg({"chunk_id": ",".join, "edge": ','.join, 'count': 'sum'})
    .reset_index()
)
dfg

,node_1,node_2,chunk_id,edge,count
0,56 articles,extensive literature search,"d7a3e5085c7f4de4bc28fb0bd9cb0a94,d7a3e5085c7f4...",contextual proximity,2
1,[54],increasing violence against healthcare personnel,"640835e2521045a395ab6465cc1ba4ca,640835e252104...",contextual proximity,2
2,[55],increasing violence against healthcare personnel,"640835e2521045a395ab6465cc1ba4ca,640835e252104...",contextual proximity,2
3,a bad situation,increasing violence against healthcare personnel,"640835e2521045a395ab6465cc1ba4ca,640835e252104...",contextual proximity,2
4,a worrisome new trend,increasing violence against healthcare personnel,"640835e2521045a395ab6465cc1ba4ca,640835e252104...",contextual proximity,2
...,...,...,...,...,...
753,world-class health facilities,nhm strategies,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",contextual proximity,10
754,world-class health facilities,rural areas,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",contextual proximity,2
755,world-class health facilities,social norms,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",contextual proximity,2
756,world-class health facilities,urban areas,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",contextual proximity,2
757,world-class health facilities,urban slums,"0857ab4513ad4383aed095bcf24506fa,0857ab4513ad4...",contextual proximity,2

## Calculate the NetworkX Graph

In [9]:
nodes = pd.concat([dfg['node_1'], dfg['node_2']], axis=0).unique()
nodes.shape

(215,)

In [10]:
import networkx as nx
G = nx.Graph()

## Add nodes to the graph
for node in nodes:
    G.add_node(
        str(node)
    )

## Add edges to the graph
for index, row in dfg.iterrows():
    G.add_edge(
        str(row["node_1"]),
        str(row["node_2"]),
        title=row["edge"],
        weight=row['count']/4
    )

### Calculate communities for coloring the nodes

In [11]:
communities_generator = nx.community.girvan_newman(G)
top_level_communities = next(communities_generator)
next_level_communities = next(communities_generator)
communities = sorted(map(sorted, next_level_communities))
print("Number of Communities = ", len(communities))
print(communities)

Number of Communities =  17
[['56 articles', 'analysis', "corresponding authors' experiential knowledge", 'extensive literature search', 'peer-reviewed journals'], ['[54]', '[55]', 'a bad situation', 'a worrisome new trend', 'adequately compensated', 'can reverse the situation', 'defensive medicine practices', 'increasing violence against healthcare personnel', 'intense focus on specialization', 'low physician-to-patient ratio', 'overwhelmed physicians', 'primary care physicians', 'private marketplace', 'protect themselves by ordering unnecessary tests and procedures', 'results in delays in attending patients', 'set in', 'tempted to take on more patients than they can reasonably serve', 'thoughtful approach to government planning', 'underpaid physicians', 'unethical practices by pharmaceutical companies', 'will not be able to solve this'], ['accredit health facilities', 'enforcement of existing rules', 'health insurance scheme for central government employees', 'health system standardization', 'implementation of land allocation conditions', 'medical tourism hub', 'new rules for reasonable costs and cap profit margins', 'private health sector regulation', 'private health sector utilization'], ['accurate data about the quantity and geospatial location of its manpower', "central government's leadership in the fight for better health for all indians", 'live register for health personnel and infrastructure'], ['adoption', 'affordable, accessible, quality care', 'clinical and social skills', 'corporate houses', 'deeper structural problems', 'doctor-to-population ratio', 'erratic posting of personnel', 'evaluations', 'for-profit private health sector', 'government', 'government-funded health sector', 'health infrastructure', 'health personnel', 'health system', 'implementation', 'individualized mentoring', 'medical tourism', 'narayana health', 'national health mission (nhm)', 'non-hierarchical work environment', 'online training', 'out-of-pocket (oop) expenditure', 'out-of-pocket expenditure', 'overarching', 'patients', 'personnel retention', 'physicians', 'policy', 'primary care', 'private health sector', 'providing ongoing training', 'public and private health sectors', 'public health sector', 'public hospital beds', 'quality care', 'quality of care', 'quantum of services provided', 'recommendations made here', 'regulation', 'retaining', 'service provision', 'services they have been trained for', 'sourcing health personnel', 'strengthening', 'tier ii and iii cities', 'training', 'training initiative', 'transparency', 'transparency in creating training schedules', 'uniform standards', 'unmet demand for healthcare services', 'upgrading skills of nurses', 'vulnerable populations', 'well-equipped personnel', 'work environment', "world health organization's recommended"], ['ai-embedded logarithms now diagnose covid-19 disease from chest x-rays and ct scans', 'covid-19 pandemic catalyzing process and enabling delivery of healthcare', 'doctors can now perform an ophthalmic fundal examination online', 'drones being used to deliver medicines to communities', 'expanding application of technology to other portfolios within the health sector', 'innovations in digital technology supporting delivery of vital healthcare in high-income countries', 'manufacturing protective equipment locally using 3d printing', 'remote orthopedic examinations being used successfully', 'telemedicine for consultations with healthcare providers', 'uptake of telemedicine during covid-19 pandemic'], ['allocated budget to healthcare', 'ashas', 'ayush doctors', 'ayushman bharat', 'cadres', 'communities', 'communitization', 'contractors', 'contracts', 'contractual employees', 'contractual personnel', 'delayed', 'demotivation', 'doctors', 'economic norms', 'epidemiology/public health', 'financially protected from catastrophic health expenses', 'flexible financing', 'gdp', 'government of india', 'health policy', 'health sector reform', 'healthcare facilities', 'high-income countries', 'improved management through capacity building', 'india', 'indian government', 'indian-born physicians', 'informal providers', 'infrastructure', 'innovations in human resource management', 'just over $30 billion', 'largest émigré physician workforce in the world', 'lower remuneration', 'monitoring progress against standards', 'nhm', 'nhm strategies', 'nurses', 'oop expenditures by consumers', 'other middle-income countries and its neighbors', 'poor', 'poor infrastructure', 'public health', 'public sector', 'publicly financed health insurance scheme for the poor', 'publicly financed purchasing of services from private providers', 'rural areas', 'salary payments', 'skilled health workforce', 'social norms', 'temporary nature', 'total expenditure on health in india', 'urban areas', 'urban slums', 'viability concerns', 'working conditions', 'world-class health facilities'], ['anm', 'asha', 'female community health workers', 'government employee', 'private contractor'], ['centralization', 'interplay between private corporate sector, pharmaceutical industries, medical education, and healthcare services', 'medical commission', 'medical education', 'national medical council (nmc)', 'nmc act', 'state', 'universal health coverage'], ["constraints imposed by corporate healthcare sector on doctors' professional autonomy", 'doctors gravitating towards private sector employment due to low government salaries', 'high fees of private sector medical colleges', 'higher number of medical colleges per population in india compared to other countries', 'highest employer of doctors in india', 'highly paid doctors graduating from private sector medical colleges', 'low fees of government medical colleges', 'majority of young and early career doctors facing erosion of status and opportunities in the private healthcare sector', "performance targets and practice constraints on doctors' professional autonomy in the corporate healthcare sector", 'private sector healthcare employment', 'private sector investment in medical colleges', 'profitable medical colleges', 'star doctors with flourishing practices in the private healthcare sector'], ['digital technology', 'evin', 'medical devices', 'online training management information systems', 'wearable, trackable technology'], ['doctors and nurses/midwives', 'health workers density'], ['federal', 'health budget'], ["india's health indicators", 'methodology used', 'national medical council', 'peer nations', 'private sector', 'public-private sector divide', 'read approach', 'recent increase in the federal health budget', 'skewed inter-state', 'skilled personnel', 'urban-rural', 'who recommended thresholds'], ['initial evaluation', 'primary health centers', 'rural medical assistants (rmas)'], ['limited uptake', 'national health protection mission'], ['private health sector systems', 'public']]

### Create a dataframe for community colors

In [12]:
import seaborn as sns
palette = "hls"

## Now add these colors to communities and make another dataframe
def colors2Community(communities) -> pd.DataFrame:
    ## Define a color palette
    p = sns.color_palette(palette, len(communities)).as_hex()
    random.shuffle(p)
    rows = []
    group = 0
    for community in communities:
        color = p.pop()
        group += 1
        for node in community:
            rows += [{"node": node, "color": color, "group": group}]
    df_colors = pd.DataFrame(rows)
    return df_colors


colors = colors2Community(communities)
colors

                                              node    color  group
0                                      56 articles  #db57ac      1
1                                         analysis  #db57ac      1
2    corresponding authors' experiential knowledge  #db57ac      1
3                      extensive literature search  #db57ac      1
4                           peer-reviewed journals  #db57ac      1
..                                             ...      ...    ...
210                rural medical assistants (rmas)  #575edb     15
211                                 limited uptake  #9ddb57     16
212             national health protection mission  #9ddb57     16
213                  private health sector systems  #578ddb     17
214                                         public  #578ddb     17

[215 rows x 3 columns]

### Add colors to the graph

In [13]:
for index, row in colors.iterrows():
    G.nodes[row['node']]['group'] = row['group']
    G.nodes[row['node']]['color'] = row['color']
    G.nodes[row['node']]['size'] = G.degree[row['node']]

In [17]:
from pyvis.network import Network

graph_output_directory = "./docs/index.html"

net = Network(
    notebook=False,
    # bgcolor="#1a1a1a",
    cdn_resources="remote",
    height="900px",
    width="100%",
    select_menu=True,
    # font_color="#cccccc",
    filter_menu=False,
)

net.from_nx(G)
# net.repulsion(node_distance=150, spring_length=400)
net.force_atlas_2based(central_gravity=0.015, gravity=-31)
# net.barnes_hut(gravity=-18100, central_gravity=5.05, spring_length=380)
net.show_buttons(filter_=["physics"])

net.show(graph_output_directory, notebook=False)

./docs/index.html